language: python
virtualenv:
  system_site_packages: true
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
env:
  - PACKAGES=true
install:
  - pip install setuptools --upgrade
  - pip install -e .[test]
# command to run tests
script:
  - ./bin/nosetests --with-coverage
